package com.coderman.club.plugins;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import org.apache.commons.lang3.StringUtils;
import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.PluginAdapter;
import org.mybatis.generator.api.dom.java.*;
import org.mybatis.generator.api.dom.xml.XmlElement;

import java.io.Serializable;
import java.util.List;

/**
 * @author coderman
 * @Title: mybatis生成model 插件
 * @Description: model 插件
 * @date 2022/5/2322:40
 */
/**
 * @author zhangyukang
 * @Title: mybatis生成model 插件
 * @Description: model 插件
 * @date 2022/5/2322:40
 */
public class MybatisModelPlugin extends PluginAdapter {


    /**
     * 在插件被执行之前被调用，用于验证插件的配置是否正确。
     *
     * @param warnings 参数用于返回验证过程中的警告消息
     * @return
     */
    @Override
    public boolean validate(List<String> warnings) {
        return true;
    }

    public MybatisModelPlugin() {
    }


    /**
     * 用于在生成 Model（实体类）的基础记录类（BaseRecord）时执行自定义逻辑。
     *
     * @param topLevelClass
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean modelBaseRecordClassGenerated(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {

        String tableName = introspectedTable.getFullyQualifiedTableNameAtRuntime();

        // 添加类注释
        topLevelClass.addJavaDocLine("/**");
        topLevelClass.addJavaDocLine(" * This is the base record class for table: " + introspectedTable.getFullyQualifiedTable());
        topLevelClass.addJavaDocLine(" * Generated by MyBatis Generator.");
        topLevelClass.addJavaDocLine(" * @author coderman - MyBatis Generator");
        topLevelClass.addJavaDocLine(" */");

        // 公共的Model
        FullyQualifiedJavaType serializable = new FullyQualifiedJavaType(Serializable.class.getName());

        // 导入包
        topLevelClass.addImportedType(Data.class.getName());
        topLevelClass.addImportedType(ApiModel.class.getName());
        topLevelClass.addImportedType(serializable);

        // 添加父类
        topLevelClass.addSuperInterface(serializable);

        // 添加注解
        topLevelClass.addAnnotation("@" + Data.class.getSimpleName());
        topLevelClass.addAnnotation("@" + ApiModel.class.getSimpleName() + "(value=\"" + topLevelClass.getType().getShortName() + "\", description = \"" + tableName + " 实体类\")");
        return true;
    }


    /**
     * 用于在生成 Model（实体类）的字段时执行自定义逻辑。
     *
     * @param field
     * @param topLevelClass
     * @param introspectedColumn
     * @param introspectedTable
     * @param modelClassType
     * @return
     */
    @Override
    public boolean modelFieldGenerated(Field field, TopLevelClass topLevelClass, IntrospectedColumn introspectedColumn,
                                       IntrospectedTable introspectedTable, ModelClassType modelClassType) {

        // 当前字段是否为主键
        boolean isPrimary = false;
        List<IntrospectedColumn> primaryKeyColumns = introspectedTable.getPrimaryKeyColumns();
        for (IntrospectedColumn primaryKeyColumn : primaryKeyColumns) {
            if (field.getName().equals(primaryKeyColumn.getJavaProperty())) {
                isPrimary = true;
                break;
            }
        }

        // 获取备注信息
        String remarks = introspectedColumn.getRemarks();
        if (StringUtils.isEmpty(remarks)) {
            remarks = StringUtils.EMPTY;
        }

        // 备注里面可能有特殊字符，这里进行转义一下
        field.addAnnotation("@" + ApiModelProperty.class.getSimpleName() + "(value = \"" + remarks + "\")");

        // 为主键时添加一行换行
        if (isPrimary) {
            field.addJavaDocLine(StringUtils.LF);
        }

        boolean needTableField = false;

        // 如果字段里面没有下划线，并且是驼峰命名的，需要加上 @TableField 注解进行标示. (或者存在数值的情况)
        String actualColumnName = introspectedColumn.getActualColumnName();
        boolean c1 = !StringUtils.contains(actualColumnName, "_") && isCamelCase(actualColumnName);
        boolean c2 = StringUtils.contains(actualColumnName, "_") && actualColumnName.matches(".*\\d+.*");
        if (c1 || c2) {
            field.addAnnotation("@" + TableField.class.getSimpleName() + "( \"`" + actualColumnName + "`\")");
            needTableField = true;
        }

        // 导入包
        if (needTableField) {
            topLevelClass.addImportedType(TableField.class.getName());
        }

        // 导入包
        topLevelClass.addImportedType(ApiModelProperty.class.getName());

        // 改变实体类中的属性,
        if (c1) {
            field.setName(actualColumnName);
            introspectedColumn.setJavaProperty(actualColumnName);
        }

        return true;
    }

    /**
     * 判断字段是否为Java驼峰风格
     * <p>
     * 匹配首字母小写，后续单词首字母大写的格式
     *
     * @param str 原字符串
     * @return
     */
    public static boolean isCamelCase(String str) {
        if (str == null || str.isEmpty()) {
            return false;
        }
        return str.matches("^[a-z]+[A-Z][a-zA-Z]*$");
    }

    /**
     * 用于在生成 Mapper 接口（也称为 DAO 接口）时执行自定义逻辑。
     *
     * @param interfaze
     * @param topLevelClass
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean clientGenerated(Interface interfaze, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {

        // 添加Mapper类注释
        interfaze.addJavaDocLine("/**");
        interfaze.addJavaDocLine(" * This is the base Mapper class for table: " + introspectedTable.getFullyQualifiedTable());
        interfaze.addJavaDocLine(" * Generated by MyBatis Generator.");
        interfaze.addJavaDocLine(" * @author 亚声威格 - MyBatis Generator");
        interfaze.addJavaDocLine(" */");

        // 公共DAO
        FullyQualifiedJavaType baseJavaType = new FullyQualifiedJavaType(BaseMapper.class.getName());

        // 泛型类
        FullyQualifiedJavaType recordJavaType = new FullyQualifiedJavaType(introspectedTable.getBaseRecordType());

        // 导入包
        interfaze.addImportedType(baseJavaType);
        interfaze.addImportedType(recordJavaType);

        // 添加泛型
        FullyQualifiedJavaType argumentJavaType = new FullyQualifiedJavaType(BaseMapper.class.getName());
        argumentJavaType.addTypeArgument(recordJavaType);

        // 添加父类接口
        interfaze.addSuperInterface(argumentJavaType);

        return true;
    }


    /**
     * countByExample
     * @param method
     * @param interfaze
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean clientCountByExampleMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable) {
        return false;
    }
    @Override
    public boolean clientCountByExampleMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    /**
     * deleteByExample
     * @param method
     * @param interfaze
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean clientDeleteByExampleMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable) {
        return false;
    }
    @Override
    public boolean clientDeleteByExampleMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    /**
     * deleteByPrimaryKey
     * @param method
     * @param interfaze
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean clientDeleteByPrimaryKeyMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable) {
        return false;
    }
    @Override
    public boolean clientDeleteByPrimaryKeyMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    /**
     * insert
     * @param method
     * @param interfaze
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean clientInsertMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable) {
        return false;
    }
    @Override
    public boolean clientInsertMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    /**
     * selectByExampleWithBLOBs
     * @param method
     * @param interfaze
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean clientSelectByExampleWithBLOBsMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable) {
        return false;
    }
    @Override
    public boolean clientSelectByExampleWithBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    /**
     * selectByExampleWithoutBLOBs
     * @param method
     * @param interfaze
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean clientSelectByExampleWithoutBLOBsMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable) {
        return false;
    }
    @Override
    public boolean clientSelectByExampleWithoutBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    /**
     * selectByPrimaryKey
     * @param method
     * @param interfaze
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean clientSelectByPrimaryKeyMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable) {
        return false;
    }
    @Override
    public boolean clientSelectByPrimaryKeyMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    /**
     * updateByExampleSelective
     * @param method
     * @param interfaze
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean clientUpdateByExampleSelectiveMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable) {
        return false;
    }
    @Override
    public boolean clientUpdateByExampleSelectiveMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    /**
     * updateByExampleWithBLOBs
     * @param method
     * @param interfaze
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean clientUpdateByExampleWithBLOBsMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable) {
        return false;
    }
    @Override
    public boolean clientUpdateByExampleWithBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    /**
     * updateByExampleWithoutBLOBs
     * @param method
     * @param interfaze
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean clientUpdateByExampleWithoutBLOBsMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable) {
        return false;
    }
    @Override
    public boolean clientUpdateByExampleWithoutBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    /**
     * updateByPrimaryKeySelective
     * @param method
     * @param interfaze
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean clientUpdateByPrimaryKeySelectiveMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable) {
        return false;
    }
    @Override
    public boolean clientUpdateByPrimaryKeySelectiveMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    /**
     * updateByPrimaryKeyWithBLOBs
     * @param method
     * @param interfaze
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean clientUpdateByPrimaryKeyWithBLOBsMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable) {
        return false;
    }
    @Override
    public boolean clientUpdateByPrimaryKeyWithBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    /**
     * updateByPrimaryKeyWithoutBLOBs
     * @param method
     * @param interfaze
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean clientUpdateByPrimaryKeyWithoutBLOBsMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable) {
        return false;
    }
    @Override
    public boolean clientUpdateByPrimaryKeyWithoutBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    /**
     * insertSelective
     * @param method
     * @param interfaze
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean clientInsertSelectiveMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable) {
        return false;
    }
    @Override
    public boolean clientInsertSelectiveMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    /**
     * 是否生成getter and setter 方法
     * @param method
     * @param topLevelClass
     * @param introspectedColumn
     * @param introspectedTable
     * @param modelClassType
     * @return
     */
    @Override
    public boolean modelGetterMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedColumn introspectedColumn, IntrospectedTable introspectedTable, ModelClassType modelClassType) {
        return false;
    }
    @Override
    public boolean modelSetterMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedColumn introspectedColumn, IntrospectedTable introspectedTable, ModelClassType modelClassType) {
        return false;
    }

    /**
     * xml
     * @param element
     * @param introspectedTable
     * @return
     */
    @Override
    public boolean sqlMapExampleWhereClauseElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean sqlMapUpdateByExampleSelectiveElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean sqlMapUpdateByExampleWithBLOBsElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean sqlMapUpdateByExampleWithoutBLOBsElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean sqlMapUpdateByPrimaryKeySelectiveElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean sqlMapUpdateByPrimaryKeyWithBLOBsElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean sqlMapUpdateByPrimaryKeyWithoutBLOBsElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean sqlMapSelectByExampleWithoutBLOBsElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean sqlMapSelectByExampleWithBLOBsElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean sqlMapSelectByPrimaryKeyElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean providerSelectByExampleWithBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean providerSelectByExampleWithoutBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean providerDeleteByExampleMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean sqlMapDeleteByPrimaryKeyElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean sqlMapInsertElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean sqlMapInsertSelectiveElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean sqlMapCountByExampleElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return false;
    }

    @Override
    public boolean sqlMapDeleteByExampleElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return false;
    }
}

