package com.coderman.club.model.post;

import com.coderman.club.model.common.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * This is the base record class for table: club_post_tag
 * Generated by MyBatis Generator.
 * @author MyBatis Generator
 */
@EqualsAndHashCode(callSuper = true)
@Data
@ApiModel(value="PostTagModel", description = "club_post_tag 实体类")
public class PostTagModel extends BaseModel {
    

    @ApiModelProperty(value = "主键id")
    private Long postTagId;

    @ApiModelProperty(value = "帖子id")
    private Long postId;

    @ApiModelProperty(value = "标签")
    private String tagName;
}