package com.coderman.club.model.post;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * This is the base record class for table: club_post
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="PostModel", description = "club_post 实体类")
@TableName(value = "club_post")
public class PostModel implements Serializable {

    @TableId(value = "post_id",type = IdType.AUTO)
    @ApiModelProperty(value = "主键id")
    private Long postId;

    @ApiModelProperty(value = "发帖用户id")
    private Long userId;

    @ApiModelProperty(value = "帖子所属板块")
    private Long sectionId;

    @ApiModelProperty(value = "帖子标题")
    private String title;

    @ApiModelProperty(value = "浏览量")
    private Integer viewsCount;

    @ApiModelProperty(value = "点赞量")
    private Integer likesCount;

    @ApiModelProperty(value = "评论量")
    private Integer commentsCount;

    @ApiModelProperty(value = "收藏量")
    private Integer favoritesCount;

    @ApiModelProperty(value = "创建时间")
    private Date createdAt;

    @ApiModelProperty(value = "最后更新时间")
    private Date lastUpdatedAt;

    @ApiModelProperty(value = "是否启用")
    private Boolean isActive;

    @ApiModelProperty(value = "是否为草稿")
    private Boolean isDraft;

    @ApiModelProperty(value = "内容")
    private String content;
}