package com.coderman.club.model.post;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * This is the base record class for table: club_post_like
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="PostLikeModel", description = "club_post_like 实体类")
@TableName(value = "club_post_like")
public class PostLikeModel implements Serializable {

    @TableId(value = "post_like_id",type = IdType.AUTO)
    @ApiModelProperty(value = "主键id")
    private Long postLikeId;

    @ApiModelProperty(value = "用户id")
    private Long userId;

    @ApiModelProperty(value = "帖子id")
    private Long postId;

    @ApiModelProperty(value = "点赞状态")
    private String status;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;
}