package com.coderman.club.model.post;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

/**
 * This is the base record class for table: club_post_tag
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="PostTagModel", description = "club_post_tag 实体类")
@TableName(value = "club_post_tag")
public class PostTagModel implements Serializable {


    @TableId(value = "post_tag_id",type = IdType.AUTO)
    @ApiModelProperty(value = "主键id")
    private Long postTagId;

    @ApiModelProperty(value = "帖子id")
    private Long postId;

    @ApiModelProperty(value = "标签")
    private String tagName;
}