package com.coderman.club.model.point;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * This is the base record class for table: club_point_account
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="PointAccountModel", description = "club_point_account 实体类")
@TableName(value = "club_point_account")
public class PointAccountModel implements Serializable {

    @TableId(value = "account_id",type = IdType.AUTO)
    @ApiModelProperty(value = "主键")
    private Long accountId;

    @ApiModelProperty(value = "用户id")
    private Long userId;

    @ApiModelProperty(value = "用户编号")
    private String userCode;

    @ApiModelProperty(value = "积分余额")
    private Integer pointsBalance;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;
}