package com.coderman.club.model.point;

import com.coderman.club.model.common.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * This is the base record class for table: club_point_account
 * Generated by MyBatis Generator.
 * @author MyBatis Generator
 */
@EqualsAndHashCode(callSuper = true)
@Data
@ApiModel(value="PointAccountModel", description = "club_point_account 实体类")
public class PointAccountModel extends BaseModel {
    

    @ApiModelProperty(value = "主键")
    private Long accountId;

    @ApiModelProperty(value = "用户id")
    private Long userId;

    @ApiModelProperty(value = "用户编号")
    private String userCode;

    @ApiModelProperty(value = "积分余额")
    private Integer pointsBalance;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;
}