package com.coderman.club.mapper.post;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.dto.post.PostCommentPageDTO;
import com.coderman.club.model.post.PostCommentModel;
import com.coderman.club.vo.notification.NotificationCommentVO;
import com.coderman.club.vo.post.PostCommentVO;
import com.coderman.club.vo.post.PostReplyVO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * This is the base Mapper class for table: club_post_comment
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
public interface PostCommentMapper extends BaseMapper<PostCommentModel> {

    /**
     * 获取每个根评论的最新三条子评论
     * @param parentIds
     * @param orderByReplies
     * @return
     */
    List<PostReplyVO> getTopRepliesForComments(@Param(value = "parentIds") List<Long> parentIds, @Param(value = "orderByReplies") List<Long> orderByReplies);


    /**
     * 增加评论回复数
     *
     * @param commentId
     */
    void addReplyCount(@Param(value = "commentId") Long commentId,@Param(value = "count") Integer count);

    /**
     * 回复分页
     * @param commentId
     * @return
     */
    List<PostReplyVO> getPostReplyPage(@Param(value = "commentId") Long commentId);

    /**
     * 获取评论相关信息
     * @param commentIdList
     * @return
     */
    List<NotificationCommentVO> selectNotificationCommentVos(@Param(value = "commentIdList") List<Long> commentIdList);

    /**
     * 查询
     * @param dto
     * @return
     */
    List<PostCommentVO> selectRootCommentVos(@Param(value = "dto") PostCommentPageDTO dto);
}