package com.coderman.club.mapper.post;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.post.PostLikeModel;

/**
 * This is the base Mapper class for table: club_post_like
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface PostLikeMapper extends BaseMapper<PostLikeModel> {
}