package com.coderman.club.mapper.post;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.post.PostCommentModel;

/**
 * This is the base Mapper class for table: club_post_comment
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface PostCommentMapper extends BaseMapper<PostCommentModel> {
}