package com.coderman.club.mapper.post;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.post.PostCommentModel;
import com.coderman.club.vo.notification.NotificationCommentVO;
import com.coderman.club.vo.notification.NotificationReplyVO;
import com.coderman.club.vo.post.PostReplyVO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * This is the base Mapper class for table: club_post_comment
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
public interface PostCommentMapper extends BaseMapper<PostCommentModel> {

    /**
     * 获取每个根评论的最新三条子评论
     * @param parentIds
     * @return
     */
    List<PostCommentModel> getTopRepliesForComments(@Param(value = "parentIds") List<Long> parentIds);


    /**
     * 增加评论回复数
     *
     * @param commentId
     */
    void addReplyCount(@Param(value = "commentId") Long commentId,@Param(value = "count") Integer count);

    /**
     * 回复分页
     * @param pageSize
     * @param offsetId
     * @param commentId
     * @return
     */
    List<PostReplyVO> getPostReplyPage(@Param(value = "pageSize") Long pageSize,@Param(value = "offsetId") Long offsetId,@Param(value = "commentId") Long commentId);

    /**
     * 获取评论相关信息
     * @param commentIdList
     * @return
     */
    List<NotificationCommentVO> selectNotificationCommentVOs(@Param(value = "commentIdList") List<Long> commentIdList);

    /**
     * 获取回复信息 （消息通知）
     * @param replyIdList
     * @return
     */
    List<NotificationReplyVO> selectNotificationReplyVos(@Param(value = "replyIdList") List<Long> replyIdList);
}