package com.coderman.club.mapper.post;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.post.PostTagModel;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * This is the base Mapper class for table: club_post_tag
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface PostTagMapper extends BaseMapper<PostTagModel> {

    /**
     * 新增帖子
     * @param postId
     * @param tagList
     */
    void insertBatch(@Param(value = "postId") Long postId, @Param(value = "tagList") List<String> tagList);
}