package com.coderman.club.mapper.post;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.post.PostCollectModel;

/**
 * This is the base Mapper class for table: club_post_collect
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
public interface PostCollectMapper extends BaseMapper<PostCollectModel> {
}