package com.coderman.club.mapper.user;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.user.UserLoginLogModel;

/**
 * This is the base Mapper class for table: club_user_login_log
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface UserLoginLogMapper extends BaseMapper<UserLoginLogModel> {
}