package com.coderman.club.mapper.user;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.user.UserModel;
import org.apache.ibatis.annotations.Param;

/**
 * This is the base Mapper class for table: club_user
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface UserMapper extends BaseMapper<UserModel> {

    UserModel selectByUsername(@Param(value = "username") String username);

    UserModel selectByEmail(@Param(value = "email") String email);

    UserModel selectByMpOpenId(@Param(value = "mpOpenId") String openId);

    int insertSelectiveReturnKey(UserModel userModel);
}