package com.coderman.club.mapper.user;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.user.UserInfoModel;
import org.apache.ibatis.annotations.Param;

import java.util.Date;

/**
 * This is the base Mapper class for table: club_user_info
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
public interface UserInfoMapper extends BaseMapper<UserInfoModel> {

    int updateLastLoginTime(@Param(value = "userId") Long userId, @Param(value = "loginTime") Date date);

    UserInfoModel selectByUserId(@Param(value = "userId") Long userId);

    int updateUserInfoByUserId(UserInfoModel userInfoModel);

}