package com.coderman.club.mapper.user;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.user.UserModel;
import org.apache.ibatis.annotations.Param;

/**
 * This is the base Mapper class for table: club_user
 * Generated by MyBatis Generator.
 *
 * @author 亚声威格 - MyBatis Generator
 */
public interface UserMapper extends BaseMapper<UserModel> {

    /**
     * 根据用户名查询
     *
     * @param username 用户名
     * @return
     */
    UserModel selectByUsername(@Param(value = "username") String username);
}