package com.coderman.club.mapper.user;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.user.UserFollowingModel;

/**
 * This is the base Mapper class for table: club_user_following
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface UserFollowingMapper extends BaseMapper<UserFollowingModel> {
}