package com.coderman.club.mapper.user;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.user.UserSettingModel;

/**
 * This is the base Mapper class for table: club_user_setting
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface UserSettingMapper extends BaseMapper<UserSettingModel> {
}