server:
  port: 8989
spring:
  application:
    name: club
  datasource:
    username: root
    password: DES@402239CE2BC2750281C31F4CEA2619B91D0AE9C2129F6555
    url: jdbc:mysql://gz-cynosdbmysql-grp-4e4x79rx.sql.tencentcdb.com:23688/club_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: redis.coderman.club
    port: 6379
    password: DES@99D5518076FE8F32214D66F4B59766B7
    timeout: 5000
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 5
        max-wait: -1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
aliyun:
  oss:
    access-key-id: DES@15BF54A5AE211A5CF9D33FBC5F1DC0BBCBB930C2BCC7C3875F2EC4A83FE5B5FD
    access-key-secret: DES@C198710CB2463E594B6599BE0ABE138AAC0735B5ABBD632655095EBE8F436582
    end-point: oss-cn-shenzhen.aliyuncs.com
    bucket-name: ioss-bucket
ai:
  chatgpt:
    open-ai-url: https://openai.proxy-api.xyz/v1/chat/completions
    open-ai-key: DES@99F9DA3E437EB81ADAE1438B0B5C0C20547C5ECC771191A8BD10A4A9C092CD60F3A2585852E324E0A082578D816984B36FC1FABB7B78E961
auth:
  token-expiration: 600 #10分钟
  refresh-token-expiration: 604800
  white-list:
    - /api/sse/chatgpt
    - /api/wechat/message
    - /api/wechat/code
    - /api/wechat/subscribe
    - /api/user/login
    - /api/user/register
    - /api/user/refresh/token
    - /api/user/logout
    - /api/user/captcha
    - /api/index/sections
    - /api/index/carousels
    - /api/index
    - /api/post/page
    - /api/post/comment/page
    - /api/post/detail
logging:
  level:
    root: info
    com.coderman.club.dao: info
    com.coderman.club: info