server:
  port: 8080
spring:
  application:
    name: club
  datasource:
    username: root
    password: DES@99D5518076FE8F32214D66F4B59766B7
    url: jdbc:mysql://localhost:3306/club_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        max-active: 10
        max-idle: 5
        min-idle: 5
        max-wait: -1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
aliyun:
  oss:
    access-key-id: DES@15BF54A5AE211A5CF9D33FBC5F1DC0BBCBB930C2BCC7C3875F2EC4A83FE5B5FD
    access-key-secret: DES@C198710CB2463E594B6599BE0ABE138AAC0735B5ABBD632655095EBE8F436582
    end-point: oss-cn-shenzhen.aliyuncs.com
    bucket-name: ioss-bucket
ai:
  chatgpt:
      open-ai-url: https://chatgpt.coderman.love/v1/chat/completions
      open-ai-key: DES@ABA18499E3E3870279BD3C568207EB82970DE972A4EB0F5AA92996D1DDAAB94BCFE2B28044D7DAD81232D376BCB18F54565467DB8A4C314F5F2EC4A83FE5B5FD
logging:
    level:
      root: info
      com.coderman.club.mapper: debug
      com.coderman.club: debug