package com.coderman.club.model.user;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * This is the base record class for table: club_user_login_log
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="UserLoginLogModel", description = "club_user_login_log 实体类")
@TableName(value = "club_user_login_log")
public class UserLoginLogModel implements Serializable {


    @TableId(value = "log_id",type = IdType.AUTO)
    @ApiModelProperty(value = "主键id")
    private Long logId;

    @ApiModelProperty(value = "用户id")
    private Long userId;

    @ApiModelProperty(value = "登录时间")
    private Date loginTime;

    @ApiModelProperty(value = "登入ip")
    private String ipAddress;

    @ApiModelProperty(value = "设备信息")
    private String deviceInfo;

    @ApiModelProperty(value = "登录地址")
    private String location;
}