package com.coderman.club.model.user;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * This is the base record class for table: club_user
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="UserModel", description = "club_user 实体类")
@TableName(value="club_user")
public class UserModel implements Serializable {
    
    @TableId(value = "user_id",type = IdType.AUTO)
    @ApiModelProperty(value = "用户id")
    private Long userId;

    @ApiModelProperty(value = "用户编号")
    private String userCode;

    @ApiModelProperty(value = "用户昵称")
    private String nickname;

    @ApiModelProperty(value = "用户头像")
    private String avatar;

    @ApiModelProperty(value = "邮箱地址")
    private String email;

    @ApiModelProperty(value = "用户名")
    private String username;

    @ApiModelProperty(value = "密码")
    private String password;

    @ApiModelProperty(value = "微信公众号用户openId")
    private String mpOpenId;

    @ApiModelProperty(value = "盐值")
    private String salt;

    @ApiModelProperty(value = "账号状态")
    private String userStatus;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    @ApiModelProperty(value = "更新时间")
    private Date updateTime;
}