package com.coderman.club.model.user;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

/**
 * This is the base record class for table: club_user_setting
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="UserSettingModel", description = "club_user_setting 实体类")
@TableName(value = "club_user_setting")
public class UserSettingModel implements Serializable {

    @TableId(value = "setting_id",type = IdType.AUTO)
    @ApiModelProperty(value = "主键id")
    private Long settingId;

    @ApiModelProperty(value = "用户id")
    private Long userId;

    @ApiModelProperty(value = "设置项键名")
    private String settingKey;

    @ApiModelProperty(value = "设置项值")
    private String settingValue;
}