package com.coderman.club.model.user;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * This is the base record class for table: club_user_following
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="UserFollowingModel", description = "club_user_following 实体类")
@TableName(value = "club_user_following")
public class UserFollowingModel implements Serializable {

    @TableId(value = "follow_id",type = IdType.AUTO)
    @ApiModelProperty(value = "主键id")
    private Long followId;

    @ApiModelProperty(value = "关注者用户")
    private Long followerId;

    @ApiModelProperty(value = "被关注者用户")
    private Long followedId;

    @ApiModelProperty(value = "关注日期")
    private Date followDate;

    @ApiModelProperty(value = "关注状态")
    private String status;
}