package com.coderman.club.model.user;

import com.coderman.club.model.common.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * This is the base record class for table: club_user_setting
 * Generated by MyBatis Generator.
 * @author MyBatis Generator
 */
@EqualsAndHashCode(callSuper = true)
@Data
@ApiModel(value="UserSettingModel", description = "club_user_setting 实体类")
public class UserSettingModel extends BaseModel {
    

    @ApiModelProperty(value = "主键id")
    private Long settingId;

    @ApiModelProperty(value = "用户id")
    private Long userId;

    @ApiModelProperty(value = "设置项键名")
    private String settingKey;

    @ApiModelProperty(value = "设置项值")
    private String settingValue;
}