package com.coderman.club.model.user;

import com.coderman.club.model.common.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * This is the base record class for table: club_user_following
 * Generated by MyBatis Generator.
 * @author MyBatis Generator
 */
@EqualsAndHashCode(callSuper = true)
@Data
@ApiModel(value="UserFollowingModel", description = "club_user_following 实体类")
public class UserFollowingModel extends BaseModel {
    

    @ApiModelProperty(value = "主键id")
    private Long followId;

    @ApiModelProperty(value = "关注者用户")
    private Long followerId;

    @ApiModelProperty(value = "被关注者用户")
    private Long followedId;

    @ApiModelProperty(value = "关注日期")
    private Date followDate;

    @ApiModelProperty(value = "关注状态")
    private String status;
}