package com.coderman.club.model.message;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * This is the base record class for table: club_message_session
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="MessageSessionModel", description = "club_message_session 实体类")
@TableName(value = "club_message_session")
public class MessageSessionModel implements Serializable {

    @TableId(value = "session_id",type = IdType.AUTO)
    @ApiModelProperty(value = "会话id")
    private Long sessionId;

    @ApiModelProperty(value = "用户1 (小id)")
    private Long userOne;

    @ApiModelProperty(value = "用户2 (大id)")
    private Long userTwo;

    @ApiModelProperty(value = "最后一条消息内容")
    private String lastMessage;

    @ApiModelProperty(value = "最后发送人id")
    private Long lastUserId;

    @ApiModelProperty(value = "最后一条私信时间")
    private Date lastMessageTime;
}