package com.coderman.club.model.message;

import com.coderman.club.model.common.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * This is the base record class for table: club_message_relation
 * Generated by MyBatis Generator.
 * @author MyBatis Generator
 */
@EqualsAndHashCode(callSuper = true)
@Data
@ApiModel(value="MessageRelationModel", description = "club_message_relation 实体类")
public class MessageRelationModel extends BaseModel {
    

    @ApiModelProperty(value = "主键id")
    private Long relationId;

    @ApiModelProperty(value = "用户id")
    private Long userId;

    @ApiModelProperty(value = "消息id")
    private Long messageId;

    @ApiModelProperty(value = "会话id")
    private Long sessionId;

    @ApiModelProperty(value = "是否删除")
    private Boolean isDelete;
}