package com.coderman.club.model.message;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * This is the base record class for table: club_message
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="MessageModel", description = "club_message 实体类")
@TableName(value = "club_message")
public class MessageModel implements Serializable {

    @TableId(value = "message_id",type = IdType.AUTO)
    @ApiModelProperty(value = "消息id")
    private Long messageId;

    @ApiModelProperty(value = "回话id")
    private Long sessionId;

    @ApiModelProperty(value = "发送人id")
    private Long senderId;

    @ApiModelProperty(value = "用户id")
    private Long userId;

    @ApiModelProperty(value = "私信内容")
    private String content;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;
}