package com.coderman.club.model.message;

import com.coderman.club.model.common.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * This is the base record class for table: club_message
 * Generated by MyBatis Generator.
 * @author MyBatis Generator
 */
@EqualsAndHashCode(callSuper = true)
@Data
@ApiModel(value="MessageModel", description = "club_message 实体类")
public class MessageModel extends BaseModel {
    

    @ApiModelProperty(value = "消息id")
    private Long messageId;

    @ApiModelProperty(value = "回话id")
    private Long sessionId;

    @ApiModelProperty(value = "发送人id")
    private Long senderId;

    @ApiModelProperty(value = "用户id")
    private Long userId;

    @ApiModelProperty(value = "私信内容")
    private String content;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;
}