package com.coderman.club.model.message;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

/**
 * This is the base record class for table: club_message_relation
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="MessageRelationModel", description = "club_message_relation 实体类")
@TableName(value = "club_message_relation")
public class MessageRelationModel implements Serializable {

    @TableId(value = "relation_id",type = IdType.AUTO)
    @ApiModelProperty(value = "主键id")
    private Long relationId;

    @ApiModelProperty(value = "用户id")
    private Long userId;

    @ApiModelProperty(value = "消息id")
    private Long messageId;

    @ApiModelProperty(value = "会话id")
    private Long sessionId;

    @ApiModelProperty(value = "是否删除")
    private Boolean isDelete;

    @ApiModelProperty(value = "是否已读")
    private Boolean isRead;
}