package com.coderman.club.mapper.message;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.message.MessageSessionRelationModel;
import org.apache.ibatis.annotations.Param;

/**
 * This is the base Mapper class for table: club_message_session_relation
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
public interface MessageSessionRelationMapper extends BaseMapper<MessageSessionRelationModel> {


    /**
     *查询用户会话关联
     * @param userId
     * @param sessionId
     * @return
     */
    MessageSessionRelationModel selectUserRelation(@Param(value = "userId") Long userId, @Param(value = "sessionId") Long sessionId);

    /**
     * 清空会话未读数
     * @param targetUserId
     * @param sessionId
     */
    void updateReadCountZero(@Param(value = "userId") Long targetUserId,@Param(value = "sessionId") Long sessionId);

    /**
     * 删除用户会话关联
     * @param userId
     * @param sessionId
     */
    int updateDeleteFlag(@Param(value = "userId") Long userId,@Param(value = "sessionId") Long sessionId);
}