package com.coderman.club.mapper.message;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.message.MessageSessionModel;
import com.coderman.club.vo.message.MessageSessionVO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * This is the base Mapper class for table: club_message_session
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
public interface MessageSessionMapper extends BaseMapper<MessageSessionModel> {

    /**
     * 查询会话
     * @param userOne
     * @param userTwo
     * @return
     */
    MessageSessionModel selectSessionByUser(@Param(value = "userOne") Long userOne, @Param(value = "userTwo") Long userTwo);

    /**
     * 新增会话
     * @param messageSessionModel
     */
    void insertSelectiveReturnKey(MessageSessionModel messageSessionModel);

    /**
     * 获取用户会话
     * @param userId
     * @return
     */
    List<MessageSessionVO> selectSessionList(@Param(value = "userId") Long userId);
}