package com.coderman.club.mapper.message;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.message.MessageModel;
import com.coderman.club.vo.message.MessageVO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * This is the base Mapper class for table: club_message
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
public interface MessageMapper extends BaseMapper<MessageModel> {


    /**
     * 获取用户会话中的信息列表
     * @param userId
     * @param sessionId
     * @return
     */
    List<MessageVO> selectUserMessages(@Param(value = "userId") Long userId, @Param(value = "sessionId") Long sessionId);


    /**
     * 新增消息
     * @param messageModel
     * @return
     */
    int insertSelectiveReturnKey(MessageModel messageModel);

}