package com.coderman.club.mapper.message;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.message.MessageRelationModel;
import org.apache.ibatis.annotations.Param;

/**
 * This is the base Mapper class for table: club_message_relation
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface MessageRelationMapper extends BaseMapper<MessageRelationModel> {


    /**
     * 更新消息为已读
     *
     * @param targetUserId
     * @param sessionId
     */
    void updateReadStatus(@Param(value = "userId") Long targetUserId, @Param(value = "sessionId") Long sessionId);
}