package com.coderman.club.mapper.point;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.point.PointAccountModel;

/**
 * This is the base Mapper class for table: club_point_account
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
public interface PointAccountMapper extends BaseMapper<PointAccountModel> {
}