package com.coderman.club.model.carousel;

import com.coderman.club.model.common.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * This is the base record class for table: club_carousel
 * Generated by MyBatis Generator.
 * @author MyBatis Generator
 */
@EqualsAndHashCode(callSuper = true)
@Data
@ApiModel(value="CarouselModel", description = "club_carousel 实体类")
public class CarouselModel extends BaseModel {
    

    @ApiModelProperty(value = "主键id")
    private Long carouselId;

    @ApiModelProperty(value = "标题")
    private String title;

    @ApiModelProperty(value = "描述信息")
    private String description;

    @ApiModelProperty(value = "图片url")
    private String imageUrl;

    @ApiModelProperty(value = "跳转url")
    private String targetUrl;

    @ApiModelProperty(value = "优先级顺序")
    private Integer orderPriority;

    @ApiModelProperty(value = "是否启用")
    private Boolean isActive;
}