package com.coderman.club.model.notification;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * This is the base record class for table: club_notification
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="NotificationModel", description = "club_notification 实体类")
@TableName(value="club_notification")
public class NotificationModel implements Serializable {
    
    @TableId(value = "notification_id",type = IdType.AUTO)
    @ApiModelProperty(value = "主键")
    private Long notificationId;

    @ApiModelProperty(value = "接收通知的用户的唯一标识符")
    private Long userId;

    @ApiModelProperty(value = "发送通知的用户或系统的唯一标识符")
    private Long senderId;

    @ApiModelProperty(value = "通知的类型（例如：点赞、评论、回复、系统通知等）")
    private String type;

    @ApiModelProperty(value = "通知的具体内容")
    private String content;

    @ApiModelProperty(value = "关联的业务id")
    private Long relationId;

    @ApiModelProperty(value = "标记通知是否已被用户阅读")
    private Boolean isRead;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    @ApiModelProperty(value = "读取时间")
    private Date readTime;
}