package com.coderman.club.mapper.section;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.section.SectionModel;

/**
 * This is the base Mapper class for table: club_section
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
public interface SectionMapper extends BaseMapper<SectionModel> {
}