package com.coderman.club.mapper.carousel;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.coderman.club.model.carousel.CarouselModel;

/**
 * This is the base Mapper class for table: club_carousel
 * Generated by MyBatis Generator.
 * @author 亚声威格 - MyBatis Generator
 */
public interface CarouselMapper extends BaseMapper<CarouselModel> {
}