package com.coderman.club.model.section;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

/**
 * This is the base record class for table: club_section
 * Generated by MyBatis Generator.
 * @author coderman - MyBatis Generator
 */
@Data
@ApiModel(value="SectionModel", description = "club_section 实体类")
@TableName(value = "club_section")
public class SectionModel implements Serializable {

    @TableId(value = "section_id",type = IdType.AUTO)
    @ApiModelProperty(value = "主键id")
    private Long sectionId;

    @ApiModelProperty(value = "版块名称")
    private String sectionName;

    @ApiModelProperty(value = "父版块（可为空）")
    private Long parentSection;

    @ApiModelProperty(value = "版块描述")
    private String description;

    @ApiModelProperty(value = "是否处于启用状态")
    private Boolean isActive;

    @ApiModelProperty(value = "排序字段")
    private Integer sort;
}